version: "3.8"
services:
  db:
    image: postgres:15
    container_name: pokemon_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon
    volumes:
      - ./BD/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"